branch-defaults:
  aws:
    environment: null
    group_suffix: null
global:
  application_name: ReaCraft
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
